### ISSUE TITLE
Nice timing!

### ISSUE THREAD

**Issue by ericseppanen** [rvagg/fhex#1]
I published the [hexfloat2](https://docs.rs/hexfloat2/latest/hexfloat2/) crate within hours of you publishing this one. I find it amusing after many years of not much progress in this area we both built similar things at the same time.

So, high five, I guess :)

I like how your tests document some of the Golang and C++ behavior!

**Comment by rvagg** [comment]
Hey, that's pretty cool, and you got to parsing too - that was lower priority for me and hexf was already doing it (though I haven't tested its ability to do the right thing yet); I figured I'd eventually get to it and make a consistent round-trip utility, but parsing is less important to my needs right now at least. I'll get your crate onto my readme when I do my next round of updates.

Did you know Rust _used_ to do this in the standard library btw? https://www.cs.brandeis.edu/~cs146a/rust/doc-02-21-2015/std/f64/fn.to_str_hex.html

**Comment by ericseppanen** [comment]
That's interesting; I wonder why they dropped the std support.

I've also forked the `conv` library [here](https://github.com/ericseppanen/conv2), in the hope of modernizing the code. It's built out of a lot of dense macros, so it's a bit of a big task to sort out how the original code worked. My hope would be to maintain most of the original functionality while improving the readability of the code.
